### ISSUE TITLE
Port Phoebe's HistFactory patch to ROOT 6.24.02

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/root-curated#4]
@manuelfs Let's use this issue to track progress and problems for porting Phoebe's HistFactory patch to ROOT 6.24.00.

The main things to figure out are

- [x] What `this->_clientList.setHashTableSize(12007);` does and whether it is needed. 
- [x] Check whether the demo can be compiled and run properly
- ~~Figure out why gamma arguments are not removed properly~~

**Comment by manuelfs** [comment]
This is a preliminary commit that compiles in ROOT 6.24/00 and has Phoebe's patches
https://github.com/umd-lhcb/root/commit/2db8078491ad9e1f5ac571f92ee37b4c2cd8e50e. It has a couple of caveats as discussed below.

I started trying to compile 6.24/00 with the [6.12/06 patches](https://twiki.cern.ch/twiki/pub/LHCbPhysics/HistFactoryInfo/Patches_July2020_ROOT-6.12.04.zip). It failed with two main types of errors

- The method `setHashTableSize` does not exist in the same way any more, and it was being called in a couple of files
```
[100%] Building CXX object roofit/histfactory/CMakeFiles/HistFactory.dir/src/RooBarlowBeestonLL.cxx.o
/Users/manuelf/code/root/roofit/histfactory/src/RooBarlowBeestonLL.cxx:65:21: error: no member named 'setHashTableSize' in
      'RooSTLRefCountList<RooAbsArg>'
  this->_clientList.setHashTableSize(12007);
  ~~~~~~~~~~~~~~~~~ ^
1 error generated.
make[2]: *** [roofit/histfactory/CMakeFiles/HistFactory.dir/src/RooBarlowBeestonLL.cxx.o] Error 1
make[1]: *** [roofit/histfactory/CMakeFiles/HistFactory.dir/all] Error 2
make: *** [all] Error 2
``` 
For now, I just commented those lines out.

- The file `roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx` was just too different from the version in ROOT 6.24/00. So I found a tag that was similar to the one Phoebe may have used. She claimed in the twiki that the patches were compatible with ROOT 5.32, but didn't see any 5.32 tag around 2017, so instead I used this [5.34 tag](https://github.com/root-project/root/tree/250a360349e60dc2dc187ecaa63fc9f5f81a9d74/roofit/histfactory/src). With respect to that tag, the changes in the file were minimal
```
(base) |08:52:21|~/Desktop/fit$ diff HistoToWorkspaceFactoryFast-5.34.cxx Patches_Feb2017/HistoToWorkspaceFactoryFast.cxx 
365a366
>     histFunc->forceNumInt(kTRUE);
506,507c507,508
<     RooArgSet observableSet(observables);
<     interp.setBinIntegrator(observableSet);
---
>     //RooArgSet observableSet(observables);
>     //interp.setBinIntegrator(observableSet);
698c699
<     tot.forceNumInt();
---
>     //tot.forceNumInt();
```
so I just added those to the `HistoToWorkspaceFactoryFast.cxx` file from 6.24/00, checked out the latest `roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h` to make it compatible, and ROOT 6.24/00 compiled! 🎉

When I then tried to compile `HistFactDstTauDemo.C`, I got errors about the `RooFormulaVar` constructor
```root [0] .L HistFactDstTauDemo.C+
Info in <TMacOSXSystem::ACLiC>: creating shared library /Users/manuelf/Desktop/fit/new/./HistFactDstTauDemo_C.so
In file included from input_line_9:6:
././HistFactDstTauDemo.C:451:21: error: variable has incomplete type 'RooFormulaVar'
      RooFormulaVar poi_pull("poi_pull","(@0-0.03428)/@1",RooArgList(*poi,poierror));
                    ^
/Users/manuelf/code/build_root/include/RooGlobalFunc.h:34:7: note: forward declaration of 'RooFormulaVar'
class RooFormulaVar ;
      ^
Error in <ACLiC>: Executing '/Users/manuelf/code/build_root/bin/rootcling -v0 "--lib-list-prefix=/Users/manuelf/Desktop/fit/new/HistFactDstTauDemo_C_ACLiC_map" -f "/Users/manuelf/Desktop/fit/new/HistFactDstTauDemo_C_ACLiC_dict.cxx" -I$ROOTSYS/include -isysroot "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/" -I"/Users/manuelf/code/build_root/etc/" -I"/Users/manuelf/code/build_root/etc//cling" -I"/Users/manuelf/code/build_root/include/" -I"/Users/manuelf/code/build_root/include" -D__ACLIC__  "/Users/manuelf/Desktop/fit/new/./HistFactDstTauDemo.C" "/Users/manuelf/Desktop/fit/new/HistFactDstTauDemo_C_ACLiC_linkdef.h"' failed!
```
I also tried adding a title after `"poi_pull",`, but it complained about the same thing. So I just ran it interactively, and it went to the end and produced this plot
![c2](https://user-images.githubusercontent.com/4977423/123545436-fb9c0500-d725-11eb-98e1-5bb9c06a61af.jpg)

I won't upload the log file because it is 150 MB, but it says
```
Fit ran with status 0
Stat error on R(D*) is 0.002408
EDM at end was 0.000093
```
before printing the values of the parameters and a 641x641 matrix unity matrix. There are also lots of zeroes in the middle, so I'm not sure it is right.

Thus, the main things to figure out are

- [ ] What `this->_clientList.setHashTableSize(12007);` does and whether it is needed. 
- [ ] Check whether the demo can be compiled and run properly

**Comment by manuelfs** [comment]
The compilation error in `HistFactDstTauDemo.C` is solved simply by adding `#include "RooFormulaVar.h"` to the beginning of the file

**Comment by Svende** [comment]
@manuelfs How long did the fit take for you? There should be a an output related to that in the log file: `Stopwatch: fit ran in yyy seconds with xxx seconds in prep`. I documented the times with different ROOT versions here: https://github.com/umd-lhcb/rdx-run2-analysis/issues/32#issue-821175410

**Comment by manuelfs** [comment]
`Stopwatch: fit ran in 2779.988225 seconds with 14.988133 seconds in prep`

**Comment by Svende** [comment]
Thank you, that seems super slow compared to what I had before on ubuntu with root 6.06/02: 
```
Stopwatch: fit ran in 109.633205 seconds with 163.420054 seconds in prep
Stopwatch: fit ran in 105.913323 seconds with 157.692361 seconds in prep with +
Stopwatch: fit ran in 106.916689 seconds with 158.098260 seconds in prep with ++
Stopwatch: fit ran in 104.649853 seconds with 158.900085 s with gSystem->SetAclicMode(TSystem::kOpt) before
```

**Comment by Svende** [comment]
I get `Stopwatch: fit ran in 2008.001711 seconds with 14.625669 seconds in prep` now

**Comment by manuelfs** [comment]
Interesting, I wonder whether this is the missing `this->_clientList.setHashTableSize(12007)`

**Comment by yipengsun** [comment]
ROOT 6.24.02 just released. According to change log, it contains "some `roofit` bug fixes`.

For now, let's still focus on 6.24.00. Ideally we can still apply our patch directly to 6.24.02.

**Comment by yipengsun** [comment]
Also, I think we should name our branch like this: `histfactory_patch-v6-24-00` to be able to differentiate sub-versions between the 6.24 branch.

**Comment by yipengsun** [comment]
And we can have a stub `histfactory_patch` that points to the latest working ROOT w/ our patch applied.

**Comment by manuelfs** [comment]
Agreed, the branches should have the full tag in the name. I just committed the patches to `histfactory_patch_v5-34-38`, which was tagged on March 2018 (after Phoebe's patch), but the changes seemed minimal. As before I don't know if they compile, but I think they probably will
https://github.com/umd-lhcb/root/tree/histfactory_patch_v5-34-38

**Comment by manuelfs** [comment]
When asked about `setHashTableSize`, Phoebe explained that

> I don't actually care about the hash table size, I just wanted to force the RooArgList hash table functionality to be anabled. That way, calls to RooArgList::find("name") do a hash table lookup of the parameter name rather than traversing the list (from the beginning! for every bin!)

Instead, tried adding `paramSet.useHashMapForFind(true);` in the three `ParamHistFunc::createParamSet` constructors, but the demo still ran in 2000 seconds. 

And already we had seen a significant slowdown from ROOT 5.34/38 where it took 6 seconds (`Stopwatch: fit ran in 5.958700 seconds with 0.842561 seconds in prep`) and 6.06 where i[t took 105s](https://github.com/umd-lhcb/rdx-run2-analysis/issues/32#issue-821175410). So we will try running in those versions to see if we can get the speed up, at the risk of enraging the RooHammer gods.

On a parallel track, @Svende will ask RD+ how long the fit takes for them, which ROOT version they use, and the source code for their patches.

**Comment by manuelfs** [comment]
Tried to compile [Yipeng's latest port to 6.24/02](https://github.com/umd-lhcb/root/commit/7b287405932df009aa4a628255021a0bcc322c4b), and it has errors in Catalina
```
Scanning dependencies of target G__Core
[ 76%] Building CXX object core/CMakeFiles/G__Core.dir/G__Core.cxx.o
[ 76%] Built target G__Core
[ 76%] Linking CXX shared library ../lib/libCore.so
[ 76%] Built target Core
make[2]: *** No rule to make target `/Users/manuelf/code/root/core/thread/inc/ROOT/TReentrantRWLock.hxx', needed by `core/thread/G__Thread.cxx'.  Stop.
make[1]: *** [core/thread/CMakeFiles/G__Thread.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 76%] Generating G__complexDict.cxx, ../../lib/libcomplexDict.rootmap
[ 76%] Generating G__Rint.cxx, ../../lib/Rint.pcm
[ 76%] Generating G__valarrayDict.cxx, ../../lib/libvalarrayDict.rootmap
[ 76%] Generating G__multimapDict.cxx, ../../lib/libmultimapDict.rootmap
[ 76%] Generating G__multisetDict.cxx, ../../lib/libmultisetDict.rootmap
Scanning dependencies of target G__valarrayDict
[ 76%] Building CXX object core/clingutils/CMakeFiles/G__valarrayDict.dir/G__valarrayDict.cxx.o
Scanning dependencies of target G__multisetDict
[ 76%] Building CXX object core/clingutils/CMakeFiles/G__multisetDict.dir/G__multisetDict.cxx.o
Scanning dependencies of target G__multimapDict
[ 76%] Building CXX object core/clingutils/CMakeFiles/G__multimapDict.dir/G__multimapDict.cxx.o
Scanning dependencies of target G__complexDict
[ 76%] Building CXX object core/clingutils/CMakeFiles/G__complexDict.dir/G__complexDict.cxx.o
Scanning dependencies of target G__Rint
[ 76%] Building CXX object core/rint/CMakeFiles/G__Rint.dir/G__Rint.cxx.o
[ 76%] Built target G__valarrayDict
[ 76%] Built target G__complexDict
[ 76%] Built target G__Rint
[ 76%] Built target G__multisetDict
[ 76%] Built target G__multimapDict
make: *** [all] Error 2
```

It could be because I didn't clean up my previous compilation, trying again with 
```
rm -rf install_root build_root
mkdir install_root build_root
cd build_root/
cmake -DCMAKE_INSTALL_PREFIX=../install_root/ -Dsqlite=OFF -Dmysql=OFF -Dx11=ON  -Droofit=ON  -Dmt=ON -Dminuit2=ON -Dccache=ON -Dlibcxx=ON -Drpath=ON ../root 
cmake --build . -- install -j6
```

**Comment by manuelfs** [comment]
Indeed,  [Yipeng's latest port to 6.24/02](https://github.com/umd-lhcb/root/commit/7b287405932df009aa4a628255021a0bcc322c4b) compiled in Catalina after cleaning up the previous compilation as above, and it maintains the good convergence and speed gains of 6.24/00
```
FCN=-3035.66 FROM MINOS     STATUS=SUCCESSFUL    185 CALLS        1167 TOTAL
                     EDM=4.4189e-05    STRATEGY= 2      ERROR MATRIX ACCURATE 
  EXT PARAMETER                  PARABOLIC         MINOS ERRORS        
  NO.   NAME      VALUE            ERROR      NEGATIVE      POSITIVE   
   1  Lumi         9.39154e-01   3.53608e-02                            
   2  Nmu          6.37709e+04   4.35427e+02                            
   3  RawRDst      4.05100e-02   4.40318e-03  -4.39237e-03   4.55057e-03
...
Stopwatch: fit ran in 58.842301 seconds with 15.176403 seconds in prep
```

**Comment by yipengsun** [comment]
There's another patch that is currently not in our `root` `hist_factory` branch: https://github.com/umd-lhcb/root-curated/blob/master/nix/root/hist_factory_branch_optimization.patch

This one might provide even more performance boost. I haven't included this in our `hist_factory` branch because I am still trying to clean it up, so I don't want to introduce potentially breaking changes.

**Comment by yipengsun** [comment]
@manuelfs @CoffeeIntoScience I've cleaned up our [`hist_factory` branch](https://github.com/umd-lhcb/root). Now it should be a minimal change w.r.t. ROOT 6.24/02. This will be a better foundation if we want to add further changes to the official ROOT.

The official gammas removal procedure still doesn't work. Instead, I have to tweak Phoebe's method:
```cpp
bool RooStats::HistFactory::RooBarlowBeestonLL::getParameters(const RooArgSet* depList,
                                                              RooArgSet& outputSet,
                                                              bool stripDisconnected) const {
  bool errorInBaseCall = RooAbsArg::getParameters( depList, outputSet, stripDisconnected );

  for (auto const& arg : outputSet) {

    // If there is a gamma in the name,
    // strip it from the list of dependencies

    outputSet.remove( *outputSet.selectByName("*gamma_stat*"), kTRUE, kTRUE );

  }

  return errorInBaseCall || false;

}
```

Maybe we want to ask ROOT experts on why the official removal is not working?

I've also updated `histfactory-fitter-demo` so that ROOT 6.24/02 is a viable version of ROOT.

**Comment by yipengsun** [comment]
Also, for the code above, it looks to me that we don't need the `for` loop at all: the `selectByName` should return a `RooAbsCollection` so we only need to call it once?

**Comment by yipengsun** [comment]
BTW, it is interesting that the `-O3` optimization flag in `gcc` makes the fitter slower, compared to `-O2`:
```
Stopwatch: fit ran in 80.210066 seconds with 102.025603 seconds in prep
```

**Comment by manuelfs** [comment]
I ran a few tests on my laptop. The [latest commit to ROOT 6.24/02](https://github.com/umd-lhcb/root/commit/e3f26fdfbbfef449c41498423f418806012558b1) works in Catalina. When run interactively, the whole fit plus slow plots took 17:19 min and the stopwatch was `fit ran in 58.360980 seconds with 15.841435 seconds in prep`.

When I run 6.24/02 in nix inside `histfactory-fitter-demo` with `make fit`, the whole thing took 15:52 and the stopwatch `fit ran in 67.194643 seconds with 16.641417 seconds in prep`. It is a bit strange how after it converges the stopwatch is not printed for a few minutes, but the overall time is shorter than interactively, so it may be a quirk of how it is run.

I then ran the demo from `histfactory-fitter-demo` in Catalina compiled with 
```
clang++ -stdlib=libc++ -pthread -std=c++17 -m64 -I/Users/manuelf/code/build_root/include -O2 -o HistFactDstTauDemo.exe HistFactDstTauDemo.cpp -L/Users/manuelf/code/build_root/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -Wl,-rpath,/Users/manuelf/code/build_root/lib -stdlib=libc++ -lpthread -lm -ldl -lRooFitCore -lRooFit -lRooStats -lHistFactory

./HistFactDstTauDemo.exe . .
```
and the whole thing took 16:24 and the stopwatch `fit ran in 58.360980 seconds with 15.841435 seconds in prep`, with the difference that the stopwatch printed immediately. So it does look like it runs faster in Catalina than in nix.

Finally, I ran it again in nix in `histfactory-fitter-demo` for 6.16/00 and the whole thing was much more verbose and it took 26:16. The stopwatch was `fit ran in 75.315625 seconds with 97.409569 seconds in prep`.

**Comment by manuelfs** [comment]
By the way, I should say that of course there's some variation on the running times. I just ran it again compiled in Catalina and it took `Stopwatch: fit ran in 63.678400 seconds with 16.570266 seconds in prep`, 5 seconds slower fit. I must say that the latest commit to 6.24/02 seems to have made it a tad slower, although I'd need to run it many more times to be sure.
